insert into product (id, name, brand, madein, price) values (1, 'Pantoprazole Sodium', 'Night Time Original', 'Afghanistan', 26274);
insert into product (id, name, brand, madein, price) values (2, 'Levetiracetam', 'BOS TAURUS SKIN', 'Thailand', 21259);
insert into product (id, name, brand, madein, price) values (3, 'Marsh Elder Mixture', 'Warfarin Sodium', 'Colombia', 36383);
insert into product (id, name, brand, madein, price) values (4, 'Allergy Rescue 1', 'Alcohol Free HAND SANITIZER', 'Czech Republic', 96039);
insert into product (id, name, brand, madein, price) values (5, 'Salsolinol', 'Sulwhasoo Lumitouch Foundation', 'China', 79793);
insert into product (id, name, brand, madein, price) values (6, 'RED ORANGE SUN PACT', 'Losartan Potassium and Hydrochlorothiazide', 'Greece', 24584);
insert into product (id, name, brand, madein, price) values (7, 'Mometasone Furoate', 'Muscle and Joint HRX', 'Portugal', 32816);
insert into product (id, name, brand, madein, price) values (8, 'Losortan Potassium', 'Pore Tightening Serum', 'Czech Republic', 42493);
insert into product (id, name, brand, madein, price) values (9, 'Olanzapine', 'Metformin Hydrochloride', 'Poland', 58092);
insert into product (id, name, brand, madein, price) values (10, 'Cerebral Palsy', 'Blackberry', 'Ukraine', 56251);
insert into product (id, name, brand, madein, price) values (11, 'Mircette', 'Anti Nausea', 'Indonesia', 49431);
insert into product (id, name, brand, madein, price) values (12, 'Naproxen Tablets', 'Mosquito', 'Germany', 75746);
insert into product (id, name, brand, madein, price) values (13, 'Trihexyphenidyl Hydrochloride', 'Humco Castor Oil', 'China', 95289);
insert into product (id, name, brand, madein, price) values (14, 'Pier 1 Imports Coconut Breeze Anti-bacterial Hand Wash', 'Homeopathic Thyroid Formula', 'Cyprus', 57869);
insert into product (id, name, brand, madein, price) values (15, 'Glipizide', 'Gabapentin', 'Netherlands', 30165);
insert into product (id, name, brand, madein, price) values (16, 'clearskin', 'Gabapentin', 'China', 28481);
insert into product (id, name, brand, madein, price) values (17, 'Pomegranate Scented Hand Sanitizer', 'Carboplatin', 'Ukraine', 25962);
insert into product (id, name, brand, madein, price) values (18, 'Omeprazole Magnesium', 'Smart Sense Cough DM', 'Finland', 33876);
insert into product (id, name, brand, madein, price) values (19, 'Prednisone', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'Brazil', 83850);
insert into product (id, name, brand, madein, price) values (20, 'Spironolactone', 'Multi-Vitamin With Fluoride', 'China', 71441);
insert into product (id, name, brand, madein, price) values (21, 'MoistureWorx', 'Tranexamic Acid', 'Portugal', 63934);
insert into product (id, name, brand, madein, price) values (22, 'LOreal Paris Advanced Suncare Invisible Protect Sheer 30 Broad Spectrum SPF 30 Sunscreen', 'Dextrose', 'Sweden', 33586);
insert into product (id, name, brand, madein, price) values (23, 'IBU', 'EltaMD UV Shield', 'Croatia', 86650);
insert into product (id, name, brand, madein, price) values (24, 'Povidone Iodine Prep Pad', 'Oxygen', 'China', 21422);
insert into product (id, name, brand, madein, price) values (25, 'Sulfamethoxazole and Trimethoprim', 'Lovenox', 'Portugal', 67918);
insert into product (id, name, brand, madein, price) values (26, 'Topical Anesthetic', 'REFRESH CELLUVISC', 'Tunisia', 21063);
insert into product (id, name, brand, madein, price) values (27, 'Instant Hand Sanitizer - Cocoa Butter', 'Naprelan', 'Nepal', 79445);
insert into product (id, name, brand, madein, price) values (28, 'Mesalamine', 'TRICHOPHYTON MENTAGROPHYTES', 'Indonesia', 75212);
insert into product (id, name, brand, madein, price) values (29, 'Sheffield Pain Relief', 'Vanilla Bean Anti-bacterial foaming Hand Wash', 'Russia', 80342);
insert into product (id, name, brand, madein, price) values (30, 'DAILY MOISTURIZING', 'Chicken Meat', 'Philippines', 26659);
